### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by Rachelidekel**
I finished coding  stage-2 , I hope so.

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! You've done a great job with this project, I really like your code and how the page looks on intermediate screen resolutions, adaptive layout was implemented very good! You need to fix several issues to get more points and pass this stage, I think you can make it easily! Good luck with the refactoring ✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect text properties of `navigation__button-text`
    * Incorrect location of the `navigation__link-active` underline https://skr.sh/sGgw0n6n3nW?a
    * Incorrect distance between navigation elements inside header
    * Incorrect left space of the `search-results__title` on 1440, 768 viewports
    * Incorrect distance between `cards` and `search-results__button` on 1440, 768, 320 viewports
    * `Roboto slab` font isn't rendered on the page, because you use different values of `font-family` style inside components and inside `@font-face` rules, you need to use one value without typos
    * Incorrect width of the footer on all screen resolutions
    * Incorrect distance between footer and the end of the page on all screen resolutions
    * Incorrect width of `header` on 768, 320 viewports
    * Incorrect height of the `card` on 768, 320 viewport
    * Incorrect height of the header on 320 viewport
    * Navigation menu looks incorrectly on 320 viewport https://skr.sh/sGgQEpjQ2ly?a and should have overlay with changed opacity
    * No distance between `about` and `footer` on 320 viewport
    * Active link should be underlined in `header` https://skr.sh/sGg0jZAI4jq?a
    * `news-header` section looks incorrectly on all screen resolutions (incorrect vertical spaces of the section and spaces between elements, and the name is missing https://skr.sh/sGgzkuvnHrM?a https://skr.sh/sGg6Cet2zFD?a)
    * Incorrect width of `saved-news` on 1440, 768 viewports
    * Incorrect distance between `cards` and `footer` on 768 viewport
    * Incorrect height of the `footer` on 768, 320 viewports https://skr.sh/sGgp0vNYK8O?a
    * Sign up popup looks broken https://skr.sh/sGgA0EQV2dV?a
    * There shouldn't be empty space below the popup on 320 viewport https://skr.sh/sGgPmuqmqkc?a
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Cards should be centered horizontally on intermediate screen resolutions https://skr.sh/sGgpG6dCf91?a
    * Popup should be centered horizontally on all intermediate screen resolutions https://skr.sh/sGgp9RuoXek?a
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * BEM element can't be placed outside of its block https://skr.sh/sGg0mtaOV8V?a
    * It should be a key-value modifier instead of boolean modifier https://skr.sh/sGgPaFsfVnm?a https://skr.sh/sGgWS79A0VU?a
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * `news-header` block shouldn't be marked with `header` tag
    * `main` tag doesn't exist on `saved-news` page
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://skr.sh/sGg2wqG6ONB?a

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Hover is using correctly only on icon and should work with all button https://skr.sh/sGg9UcRax5N?a
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `popup__redirect-link` should be highlighted when focused
- [ ]  The form must have placeholders,  and there are required properties for the fields.
    * No required properties
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * https://skr.sh/sGgdhzey3CK?a
- [ ]  Images have an `alt` attribute containing appropriate values.
    * https://skr.sh/sGguYPilw4t?a
- [x]  Raster and vector images have been optimized.

## Number of points: 52

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for corrections, your project looks very good! Only several small issues are left below. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect text properties of `navigation__button-text`
    * Incorrect distance between navigation elements inside `header` https://skr.sh/sGiYX6lyyOI?a
    * Incorrect height of the header nav menu on 320 viewport https://skr.sh/sGihp6qszpP?a
    * Incorrect text properties of `news-header__title` and `news-header__keywords` 
    * There shouldn't be empty space below the popup on 320 viewport https://skr.sh/sGgPmuqmqkc?a
    * Incorrect text properties of text elements inside `seach-form__wrapper` https://skr.sh/sGiul7UWc4o?a
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * BEM element can't be placed outside of its block https://skr.sh/sGimoyhnAss?a
    * It should be a key-value modifier instead of boolean modifier https://skr.sh/sGgWS79A0VU?a
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://skr.sh/sGg2wqG6ONB?a

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `popup__redirect-link` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 72

**Comment by Rachelidekel** [comment]
Hello, I try to do my best in fixing all the comments you left me, thank you.

**Comment by FiLLa-FaS** [comment]
Hey! Your project is great, and I gladly accept it ✨. Good luck on the next diploma stage!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Pull request merged**
